#!/usr/bin/env python3

import os
import sys
import logging
from datetime import datetime
sys.path.append(os.getcwd()+"/.lib/")
sys.path.append(os.getcwd()+"/.src/")
from colors import red, white, green, reset
from _main_ import thedevilseye,args,start


if __name__=="__main__":
	if args.verbose:
		logging.basicConfig(format=f"{white}[{green}*{white}] %(message)s{reset}",level=logging.DEBUG)
		
	# Main loop
	while True:
		try:
			thedevilseye(args).on_connection()
			
		except KeyboardInterrupt:
			if args.verbose:
				print(f"\n{white}[{red}x{white}] Interrupted with {red}Ctrl{white}+{red}C{reset}")
				exit(f"{white}[{green}-{white}] Stopped in {green}{datetime.now()-start}{white} seconds.{reset}")	
			break
		
		except Exception as e:
			if args.verbose:
				print(f"{white}[{red}!{white}] Error: {red}{e}{reset}")
